package poo.desafio_004;

import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author jeffe
 */
public class InterfaceGrafica extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName());

    private LocalTime hora = LocalTime.now();
    private LocalTime entrada = LocalTime.now();
    private LocalTime saida = LocalTime.now();
    private LocalTime horarioLimite = LocalTime.of(18, 0);
    private LocalTime horarioAntes = LocalTime.of(7, 0);

    DecimalFormat df = new DecimalFormat("###,##0.00");

    DateTimeFormatter hf = DateTimeFormatter.ofPattern("HH:mm");

    LocalDate dt = LocalDate.now();
    DateTimeFormatter dataFormatada = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    String data = dt.format(dataFormatada);

    /**
     * Creates new form InterfaceGrafica
     */
    public InterfaceGrafica() {
        initComponents();

        //Cantos arredondados nos campos de texto
        txtPlaca.putClientProperty("JComponent.roundRect", true);
        txtModelo.putClientProperty("JComponent.roundRect", true);
        txtEntrada.putClientProperty("JComponent.roundRect", true);
        txtSaida.putClientProperty("JComponent.roundRect", true);
        txtHora.putClientProperty("JComponent.roundRect", true);

        //Placeholders (textto de dica dentro do campo)
        txtPlaca.putClientProperty("JTextField.placeholderText", "Digite a placa do Veiculo...");
        txtModelo.putClientProperty("JTextField.placeholderText", "Digite o modelo do Veiculo...");

        //Clear Button
        txtPlaca.putClientProperty("JTextField.showClearButton", true);
        txtModelo.putClientProperty("JTextField.showClearButton", true);

    }

    public void Limpar() {
        txtModelo.setText("");
        txtPlaca.setText("");
        txtEntrada.setText("");
        txtSaida.setText("");
        txaTicket.setText("");
    }

    public void entradaPermitida() {
        if (entrada.isAfter(horarioLimite)) {
            JOptionPane.showMessageDialog(this, "Estabelecimento Fechado! Volte amanhã");
        } else if (entrada.isBefore(horarioAntes)) {
            JOptionPane.showMessageDialog(this, "Estabelecimento Fechado! Aguarde o Estacionamento abrir");
        } else {
            txtEntrada.setText(hf.format(entrada));
        }
    }

    public void saidaPermitida() {
        if (saida.isAfter(horarioLimite)) {
            JOptionPane.showMessageDialog(this, "Estabelecimento Fechado! Volte amanhã");
        } else if (saida.isBefore(horarioAntes)) {
            JOptionPane.showMessageDialog(this, "Estabelecimento Fechado! Aguarde o Estacionamento abrir");
        } else {
            txtSaida.setText(hf.format(saida));
        }
    }

    public void botaoTicket() {
        try {
            String modelo = txtModelo.getText();
            String placa = txtPlaca.getText();

            if (modelo.isEmpty() || placa.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Prencha o campo de Modelo e de Placa.");
                return;
            }

            Servico servico = null;

            if (rbEstacionamento.isSelected()) {
                servico = new Estacionamento(entrada, saida, modelo, placa);
            } else if (rbLavagemS.isSelected()) {
                servico = new Estetica(modelo, placa, "Simples");
            } else if (rbLavagemC.isSelected()) {
                servico = new Estetica(modelo, placa, "Completa");
            }

            double valorPagar = servico.calcularTotal();

            StringBuilder sb = new StringBuilder();
            sb.append("========== Garbage Collector Park ==========\n\n");
            sb.append("Data: ").append(data).append("\n");
            sb.append("Modelo: ").append(modelo).append("\n");
            sb.append("Placa: ").append(placa).append("\n");
            sb.append("Horário de entrada: ").append(hf.format(entrada)).append("\n");
            sb.append("Horário de saída: ").append(hf.format(saida)).append("\n\n");
            sb.append("VALOR TOTAL A PAGAR: R$").append(df.format(valorPagar)).append("\n");

            txaTicket.setText(sb.toString());

        } catch (java.lang.NullPointerException e) {
            JOptionPane.showMessageDialog(null, "ERRO: Você precisa prencher as opções.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        rbEstacionamento = new javax.swing.JRadioButton();
        rbLavagemS = new javax.swing.JRadioButton();
        rbLavagemC = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        btnEntrada = new javax.swing.JButton();
        btnSaida = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaTicket = new javax.swing.JTextArea();
        txtEntrada = new javax.swing.JTextField();
        txtSaida = new javax.swing.JTextField();
        btnTicket = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        txtHora = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\jeffe\\Downloads\\Horário de Funcionamento (1).png")); // NOI18N

        txtModelo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtPlaca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        buttonGroup1.add(rbEstacionamento);
        rbEstacionamento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbEstacionamento.setForeground(new java.awt.Color(160, 148, 116));
        rbEstacionamento.setText("ESTACIONAMENTO COMUM: COBRADO POR HORA (R$ 10,00/hora)");

        buttonGroup1.add(rbLavagemS);
        rbLavagemS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbLavagemS.setForeground(new java.awt.Color(160, 148, 116));
        rbLavagemS.setSelected(true);
        rbLavagemS.setText("LAVAGEM SIMPLES: VALOR FIXO (R$ 40,00)");
        rbLavagemS.setActionCommand("LAVAGEM SIMPLES: VALOR FIXO (R$ 40,00)");

        buttonGroup1.add(rbLavagemC);
        rbLavagemC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbLavagemC.setForeground(new java.awt.Color(160, 148, 116));
        rbLavagemC.setText("LAVAGEM COMPLETA: VALOR FIXO (R$ 70,00)");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 88, 42));
        jLabel6.setText("ESCOLHA UM DOS SERVIÇOS");

        btnEntrada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEntrada.setText("ENTRADA");
        btnEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntradaMouseClicked(evt);
            }
        });
        btnEntrada.addActionListener(this::btnEntradaActionPerformed);

        btnSaida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSaida.setText("SAIDA");
        btnSaida.addActionListener(this::btnSaidaActionPerformed);

        txaTicket.setColumns(20);
        txaTicket.setRows(5);
        txaTicket.setEnabled(false);
        jScrollPane1.setViewportView(txaTicket);

        txtEntrada.setEditable(false);
        txtEntrada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtSaida.setEditable(false);
        txtSaida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnTicket.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTicket.setText("GERAR TICKET");
        btnTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTicketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTicketMouseExited(evt);
            }
        });
        btnTicket.addActionListener(this::btnTicketActionPerformed);

        btnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.setPreferredSize(new java.awt.Dimension(74, 27));
        btnLimpar.addActionListener(this::btnLimparActionPerformed);

        txtHora.setEditable(false);
        txtHora.setEnabled(false);
        txtHora.addActionListener(this::txtHoraActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(rbEstacionamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbLavagemS)
                                .addComponent(rbLavagemC))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTicket))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtPlaca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                .addComponent(txtModelo, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbLavagemS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbLavagemC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbEstacionamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEntrada)
                            .addComponent(btnSaida))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTicket))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaActionPerformed
        // TODO add your handling code here:
        // TEXT FIELD DA ENTRADA 
        entrada = LocalTime.now();
        entradaPermitida();
    }//GEN-LAST:event_btnEntradaActionPerformed

    private void btnSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaidaActionPerformed
        // TODO add your handling code here:
        // TEXT FIELD DA SAIDA
        saida = LocalTime.now();
        saidaPermitida();
    }//GEN-LAST:event_btnSaidaActionPerformed

    private void btnTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketActionPerformed
        // TODO add your handling code here:
        // GERAR TICKET
        botaoTicket();
    }//GEN-LAST:event_btnTicketActionPerformed

    private void btnEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntradaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntradaMouseClicked

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        Limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnTicketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTicketMouseEntered
        // TODO add your handling code here:
        if (txtEntrada.getText().isBlank() || txtSaida.getText().isBlank()) {
            btnTicket.setEnabled(false);
        }
    }//GEN-LAST:event_btnTicketMouseEntered

    private void btnTicketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTicketMouseExited
        // TODO add your handling code here:
        btnTicket.setEnabled(true);
    }//GEN-LAST:event_btnTicketMouseExited

    private void txtHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Timer timer = new Timer(1000, e -> {

            LocalTime hora = LocalTime.now();
            DateTimeFormatter hms = DateTimeFormatter.ofPattern("HH:mm:ss");
            txtHora.setText(hora.format(hms));

        });
        timer.start();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.put("Button.arc", 800);
            com.formdev.flatlaf.intellijthemes.FlatMaterialDesignDarkIJTheme.setup();
        } catch (Exception e) {
            System.out.println("Erro ao carregar o Look and Feel.");
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfaceGrafica().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrada;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSaida;
    private javax.swing.JButton btnTicket;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbEstacionamento;
    private javax.swing.JRadioButton rbLavagemC;
    private javax.swing.JRadioButton rbLavagemS;
    private javax.swing.JTextArea txaTicket;
    private javax.swing.JTextField txtEntrada;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtSaida;
    // End of variables declaration//GEN-END:variables
}
